---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp
      ver: 1.0.0
  template: 
    metadata:
      labels:
        app: testapp
        ver: 1.0.0
    spec:
      containers:
        - name: testapp
          image: httpd:latest
          ports:
            - containerPort: 80
              protocol: TCP
