---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: testapp
      ver: 1.0.0
  template: 
    metadata:
      labels:
        app: testapp
        ver: 1.0.0
    spec:
      containers:
        - name: httpd
          image: httpd:latest
          ports:
             - containerPort: 80
               protocol: TCP