---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: li
  namespace: emissary
spec:
  port: 8080
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL

